### ISSUE TITLE
Scrollbar aparece em footer

### ISSUE THREAD

**Issue by renatocfrancisco** [pedrobits/MaisCred-LandingPage#3]
Scrollbar no footer de index.html
Acho que removendo ou alterando a linha 36 de **insta.css** já resolve.

```css
.container {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  margin-top: 10px;
  overflow-x: hidden;
}
```
